config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'
  get 'dashboards/profile'
  devise_for :accounts
  resources :properties

  get "/dashboard" => 'dashboard#index', as: :dashboard
  get "/profile/:id" => 'dashboard#profile', as: :profile
  post "/agent/message" => 'properties#email_agent', as: :email_agent

  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :properties
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  has_one_attached :photo

  belongs_to :account

  scope :latest, -> { order created_at: :desc }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_account!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :company, :telephone, :first_name, :last_name, :url])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :company, :telephone, :first_name, :last_name, :url])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_sidebar

  def index
  end

  def profile
    @account = Account.find(params[:id])
  end

  private
  def set_sidebar
    @show_sidebar = true
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]
  before_action :authenticate_account!, only: %i[new create destroy]
  before_action :set_sidebar, except: [:show]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
    @agent = @property.account
    @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id)
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.account = current_account

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def email_agent
    # trigger email send
    agent_id = params[:agent_id]
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    message = params[:message]

    ContactMailer.email_agent(agent_id, first_name, last_name, email, message).deliver_now
    # response to script

    # logger.debug "First name: #{first_name}"
    # logger.debug "Last name: #{last_name}"
    # logger.debug "Email: #{email}"
    # logger.debug "message: #{message}"

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def set_sidebar
    @show_sidebar = true
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def property_params
    params.require(:property).permit(
      :name, :address, :price, :rooms, :bathrooms, :parking_spaces, :details, :for_sale, :available_date, :photo
    )
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  skip_before_action :authenticate_account!, only: :main

  def main
    if account_signed_in?
      redirect_to dashboard_path, flash: { success: "Successfully signed in. Welcome to Property Finder "} and return
    end
    @properties = Property.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_picture(account, width = 100 )
    thumb = account.avatar.present? ? account.avatar.key : "placeholder.jpg"
    cl_image_tag thumb, width: width, class: "profile-pic image-circle", alt: "profile-pic"
  end

  def flash_notifications
    flash_messages = []

    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert' || type == 'danger'
      text = "toastr[`#{type}`](`#{message}`);"
      flash_messages << text.html_safe unless message.blank?
    end

    "<script>$(function(){ #{ flash_messages.join("/n") }});</script>".html_safe if flash_messages.any?
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper

  def property_thumbnail(property)
    img = property.photo.present? ? property.photo.key : "placeholder.jpg"
    cl_image_tag img, class: "property-thumb", height: 170, width: 220, crop: :fill
  end

  # I didn't use it
  def property_thumbnail_key(property)
    img = property.photo.present? ? property.photo.key : "placeholder.jpg"
    cl_image_tag img
  end

  def property_photo(property)
    img = property.photo.present? ? property.photo.key : "placeholder.jpg"
    cl_image_tag img, class: "property-photo", height: 300, width: 400, crop: :fill
  end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/dashboard/index.html.erb
<!-- Dashboard graph and layout -->

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Dashboard</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
    </div>

    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
      This week
    </button>
  </div>
</div>

<!-- canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="826" height="348" style="display: block; width: 826px; height: 348px;"></canvas-->

<h2>Section title</h2>
<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1,001</td>
        <td>random</td>
        <td>data</td>
        <td>placeholder</td>
        <td>text</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>placeholder</td>
        <td>irrelevant</td>
        <td>visual</td>
        <td>layout</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>data</td>
        <td>rich</td>
        <td>dashboard</td>
        <td>tabular</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/dashboard/profile.html.erb
<p><%= @account.full_name %></p>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>

    <span class="text-muted">© Property Finder 2021 Company, Inc. <a href="#">Privacy</a> · <a href="#">Terms</a></span>
</footer>

app/views/layouts/_validation.html.erb
<% if item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(item.errors.count, "error") %> prohibited this property from being saved:</h2>

    <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous"-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_url "favicon/apple-touch-icon.png" %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= asset_url "favicon/favicon-32x32.png"  %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= asset_url "favicon/favicon-16x16.png" %>">
    <link rel="manifest" href="<% asset_url "favicon/site.webmanifest" %>">
  </head>

  <body id="<%= controller.controller_name %>" class="<%= controller.action_name %> <%= "show_sidebar" if @show_sidebar.present? %>" >
    <% if @show_sidebar.nil? %>
    <header>
      <%=  render "layouts/nav/public" %>
      <%= yield %>
    </header>
    <% else %>
      <%=  render "layouts/nav/dashboard" %>

      <div class="container-fluid">
        <div class="row">
          <%= render "layouts/nav/sidebar"  %>

          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-5">

          <%= yield %>
          </main>

        </div>
      </div>
    <% end %>
    <div id="notifications"><%= flash_notifications %></div>
    <p class="alert"><%= alert %></p>

    <%#= render "layouts/footer"  %>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    <script>feather.replace()</script>
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <%= link_to "Property Finder", root_path, class: "navbar-brand clo-sm-3 col-md-2 mr-0" %>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Log out", destroy_account_session_path, method: :delete, class: "nav-link"  %>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %> ">Property Finder</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <% if account_signed_in? %>
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          <% else %>
            <a class="nav-link" aria-current="page" href="#">Home</a>
          <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Latest</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">News</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Advertising</a>
        </li>
        <% if account_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_account_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<!-- Side nav for dash board-->

<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3">
    <ul class="nav flex-column">
      <li class="nav-item">
        <%= link_to dashboard_path, class: "nav-link active" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
          <b>Dashboard</b>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to properties_path, class: "nav-link" do %>
        <i data-feather="package"></i>
          <b>Properties</b>
        <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i data-feather="gift"></i>
          <b>Viewings</b>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
          <b>Contacts</b>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
          <b>Reports</b>
        </a>
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Settings</span>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <%= link_to profile_path(current_account), class: "nav-link" do %>
        <i data-feather="file-text"></i>
          <b>My Profile</b>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to edit_account_registration_path, class: "nav-link" do %>
          <i data-feather="settings"></i>
          <b>Account Settings</b>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/properties/_agent_details.html.erb
<div class="text-center border p-4 pb-4 ml-lg-4">
  <div class="mb-2">
    <%= profile_picture @agent %>
  </div>
  <h3 class="h4 m-0"><%=  @agent.full_name %></h3>
  <p><%= @agent.company %></p>

  <div class="row">
    <div class="col-12">
      <button class="btn btn-block btn-info text-uppercase mb-3" id="show-tel" data-telephone="<%= @agent.telephone %>"><i class="fas fa-phone mr-2"></i><span>Call</span></button>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 pr-1">
      <%= link_to "Profile", profile_path(@agent), class: "btn btn-secondary btn-block text-uppercase" %>
    </div>
    <div class="col-md-6 pr-1">
      <button class="btn btn-block btn-success text-uppercase" data-toggle="modal" data-target="#contact-modal">Email</button>
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <%= render "layouts/validation", item: @property %>

  <div class="form-group mb-2">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :price, "Total Price (for sale) / Monthly Price (rental) " %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :rooms %>
    <%= form.number_field :rooms, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :parking_spaces %>
    <%= form.number_field :parking_spaces, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :for_sale %>
    <%= form.select :for_sale, options_for_select({ "Yes" => true, "No" => false}, @property.for_sale), class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :available_date %>
    <%= form.date_field :available_date, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.label :details %>
    <%= form.text_area :details, class: "form-control" %>
  </div>

  <div class="form-group mb-2">
    <%= form.file_field :photo, as: :file, class: "form-control" %>
  </div>

  <% if @property.photo.present? %>
    <%= cl_image_tag @property.photo.key, height: 300, width: 400, crop: :fill, class: "m-4" %>
  <% end %>


  <div class="form-group mb-2">
    <%= form.submit "Save Property", class: "btn btn-success" %>
  </div>
<% end %>

app/views/properties/_list.html.erb
<% properties.each do |property| %>
  <div class="col-4">
    <div class="property border">
      <div class="property-thumb" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path property.photo.key%>')">
        <%= link_to "", property_path(property) %>

        </div>
        <div class="property-summary mb-2 p-3">
          <h5 class="h5"><%= link_to property.name, property_path(property), class: "text-dark" %></h5>
          <span class="mr-2">
            <%= property.rooms %>
            <i class="fas fa-bed text-muted ml-1"></i>
          </span>
          <span class="mr-2">
            <%= property.bathrooms %>
            <i class="fas fa-bath text-muted ml-1"></i>
          </span>
          <span class="mr-2">
            <%= property.parking_spaces %>
            <i class="fas fa-car text-muted ml-1"></i>
          </span>
          <p class="mt-2"><%= property.address %> </p>
        </div>
    </div>
  </div>
<% end %>

app/views/properties/_send_email_modal.html.erb
<!-- Temporary form until I fix the rails form below -->

<!--div class="modal fade" id="contact-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message for <%= @agent.first_name  %></h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">
          <span arial-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="email_agent_path" id= "email-agent">
          <div class="mb-3">
            <label for="first-name" class="col-form-label">First Name:</label>
            <input type="text" class="form-control" id="first-name">
          </div>
          <div class="mb-3">
            <label for="last-name" class="col-form-label">Last Name:</label>
            <input type="text" class="form-control" id="last-name">
          </div>
          <div class="mb-3">
            <label for="email" class="col-form-label">Email:</label>
            <input type="text" class="form-control" id="email">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success" id= "send-message-to-agent">Send message</button>
      </div>
    </div>
  </div>
</div-->

<!-- This is the Rails form I have to fix later for permanent use  -->

<div class="modal fade" id="contact-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message for <%= @agent.first_name  %></h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">
          <span arial-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag email_agent_path, id: "email-agent" do %>
          <%= hidden_field_tag :agent_id, @agent.id %>

          <div class="form-group mb-3">
            <label for="message-first-name" class="col-form-label">First Name:</label>
            <%= text_field_tag :first_name, nil, class: "form-control", id: "message-first-name" %>
          </div>

          <div class="form-group mb-3">
            <label for="message-last-name" class="col-form-label">Last Name:</label>
            <%= text_field_tag :last_name, nil, class: "form-control", id: "message-last-name" %>
          </div>

          <div class="form-group mb-3">
            <label for="message-email" class="col-form-label">Email:</label>
            <%= text_field_tag :email, nil, class: "form-control", id: "message-email" %>
          </div>

          <div class="mb-3">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-success" id= "send-message-to-agent">Send message</button>
      </div>
    </div>
  </div>
</div>

app/views/properties/edit.html.erb
<h3 class="mt-3">Editing Property</h3>

<%= render 'form', property: @property %>

app/views/properties/index.html.erb
<h1 class="h3 mt-3">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class: "btn btn-success" %>

app/views/properties/new.html.erb
<h3 class="mt-3">New Property</h3>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<div class="property-main-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @property.photo.key%>')">

  <div class="photo-overlay">

  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="row">
        <div class="col-lg-5">
          <p class="h4 mb-0"><%= @property.for_sale? ? "For Sale" : "For Rent" %></p>
          <p class="mb-2"><%= @property.address %></p>
          <p class="h2 mb-3">
            <% if @property.for_sale? %>
              <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Offers Accepted" %>
            <% else %>
              <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Open for enquiries" %> / month
            <% end %>
          </p>
        </div>
        <div class="col-lg-7 text-center">
          <div class="row mt-sm-3 bg-light-p3">
            <div class="col-4">
              <i class="fas fa-bed text-muted ml-0"></i><br>
              <small><%= @property.rooms %> Bedrooms</small>
            </div>
            <div class="col-4">
              <i class="fas fa-bath text-muted ml-0"></i><br>
              <small><%= @property.bathrooms %> Bathrooms</small>
            </div>
            <div class="col-4">
              <i class="fas fa-car text-muted ml-0"></i><br>
              <small><%= @property.parking_spaces %> Parking</small>
            </div>
          </div>
        </div>
      </div>

      <div class="row border-top border-bottom mt-4 mb-4 pt-4 pb-4">
        <div class="col-6">
          <% if @property.for_sale? %>
            <strong><%= link_to "Est. Monthly Repayments of #{number_to_currency((@property.price - (@property.price * 0.1 )) / 360, precision: 0)} *", class: "text-success" %></strong>
          <% else %>
            <strong>Available from <%= @property.available_date.strftime("%a") %>, <%= @property.available_date.day.ordinalize %> <%= @property.available_date.strftime("%B") %> </strong>
          <% end %>
        </div>
        <div class="col-6 text-right">
          <strong><%= link_to "Can I afford this property?", "#", class: "text-success"  %></strong>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <p class="h3"><%= @property.name %></p>
          <p class="h5">Property Description</p>

          <div id="prop-details">
            <%= simple_format @property.details %>
          </div>
          <button class="btn btn-outline-info mt-3 mb-3" id="toggleDetails">Show more</button>
          <% if @property.for_sale %>
            <p class="mt-5">* This rate is based on a 30 year mortgage, after paying an initial 10% down payment. Shorter term mortgages would require a higher monthly repayment</p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <%= render "properties/agent_details"  %>

      <iframe width="320" height="240" class="ml-lg-4 mt-3" src="https://maps.google.com/maps?q=<%= @property.address.to_param %>&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
    </div>
</div>

<div class="mt-2 mb-5">
  <%= link_to 'Edit Property', edit_property_path(@property), class: "btn btn-success" %> |
  <%= link_to 'Back', properties_path %>

</div>

<section class="mb-5">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <p class="h3 mb-3">Other properties by this agent</p>
      </div>
      <%= render "properties/list", properties: @agent_properties %>
    </div>
  </div>
</section>

<%= render "properties/send_email_modal"  %>